### ISSUE TITLE
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v75)，Error in if (!is.na(genome(which))) {: the condition has length > 1

### ISSUE THREAD

**Issue by wenhai-cell87** [jotsetung/EnsDb.Hsapiens.v75#2]
Hello everyone,

I hope you're doing well. I am currently working with R version 4.3.1 and following the scATAC-seq tutorial on the Signac official website. However, I encountered an error when trying to extract gene annotation information from the database.

Here is the code snippet where the issue arises:
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v75)

The error message I encountered is:
Error in if (!is.na(genome(which))) {: the condition has length > 1

I would appreciate any guidance or insights on how to resolve this error.

**Comment by jorainer** [comment]
Can you please provide the output from your `sessionInfo()`? I just tried and did not get an error. I have versions 2.26.0 for `ensembldb` and 1.12.0 for `Signac`.

Side note: the Ensembl 75 release is very old, you might eventually try to use some more recent `EnsDbs` (for more recent Ensembl releases - obviously they need to match the genome version you are using). You can get newer versions from Bioconductor's `AnnotationHub`: more information [here](https://jorainer.github.io/ensembldb/articles/ensembldb.html#getting-ensdb-databases)

**Comment by wenhai-cell87** [comment]
I have updated the versions of ensembldb，as you suggested. This seems to have resolved the issue I was encountering.Thank you for your help. I truly appreciate your support.
